[project]
name = "wg-gesucht-ir"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.3",
    "nltk>=3.9.3",
    "numpy>=2.4.2",
    "rank-bm25>=0.2.2",
    "scikit-learn>=1.8.0",
]
